defaults:
  - local: mnist
  - topology: dynamic_uniform
  - adversary: none
  - _self_

seed: 0
device: auto
result_directory: results_${local.dataset}/results-data-${local.dataset}
plot_directory: results_${local.dataset}/results-plot-${local.dataset}

hydra:
  run:
    dir: .hydra_runs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: .hydra_multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
