defaults:
  - dataset_nn: mnist
  - topology: dynamic_uniform
  - adversary: none
  - aggregator: mean
  - heterogeneity: alpha0.5
  - optimization: opt_mnist
  - evaluation: evaluation
  - _self_
  - override

nodes: 30
seed: 123
device: "cpu"

hydra:
  run:
    dir: .hydra_runs_override/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: .hydra_multirun_override/${now:%Y-%m-%d}/${now:%H-%M-%S}